apiVersion: v1
kind: Service
metadata:
  name: {{ include "crypto-forecasting.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crypto-forecasting.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "crypto-forecasting.backend.selectorLabels" . | nindent 4 }}
