apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "crypto-forecasting.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crypto-forecasting.labels" . | nindent 4 }}
data:
  {{- with .Values.configMaps.app-config.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
