apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    {{- include "crypto-forecasting.labels" . | nindent 4 }}
    app.kubernetes.io/component: namespace
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-10"
