apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: crypto-forecasting
  labels:
    app: frontend
    environment: dev
spec:
  replicas: 1  # Single replica for dev
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: crypto-forecasting-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: frontend
        image: crypto-forecasting-frontend:dev
        imagePullPolicy: Never  # Use dev images
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: "http://localhost:30050"  # Point to backend NodePort
        - name: NODE_ENV
          value: "development"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 60  # Longer delay for dev
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          limits:
            cpu: 250m      # Reduced for dev
            memory: 256Mi
          requests:
            cpu: 50m       # Lower requests for dev
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: crypto-forecasting
  labels:
    app: frontend
    environment: dev
spec:
  type: NodePort  # Use NodePort for dev access
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30030  # Fixed port for dev access