services:
  backend:
    build:
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - ml_network

  frontend:
    build:
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "8501:8501"
    networks:
      - ml_network
    depends_on:
      - backend

networks:
  ml_network:
    driver: bridge